"""postgresql_compatibility

Revision ID: 88547cb79926
Revises: f3e3ac684f8e
Create Date: 2025-11-07 17:21:16.171270

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88547cb79926"
down_revision: Union[str, Sequence[str], None] = "f3e3ac684f8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema with PostgreSQL optimizations."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create indexes for better performance on PostgreSQL

    # Index on deck_id for flashcards table (foreign key performance)
    op.create_index("ix_flashcards_deck_id", "flashcards", ["deck_id"])

    # Index on flashcard_id for reviews table (foreign key performance)
    op.create_index("ix_reviews_flashcard_id", "reviews", ["flashcard_id"])

    # Index on next_review_date for efficient due card queries
    op.create_index("ix_reviews_next_review_date", "reviews", ["next_review_date"])

    # Index on reviewed_at for sorting and analytics
    op.create_index("ix_reviews_reviewed_at", "reviews", ["reviewed_at"])

    # Index on created_at for decks and flashcards
    op.create_index("ix_decks_created_at", "decks", ["created_at"])
    op.create_index("ix_flashcards_created_at", "flashcards", ["created_at"])

    # Composite index for efficient due card filtering
    op.create_index(
        "ix_reviews_flashcard_next_review", "reviews", ["flashcard_id", "next_review_date"]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop PostgreSQL indexes
    op.drop_index("ix_reviews_flashcard_next_review")
    op.drop_index("ix_flashcards_created_at")
    op.drop_index("ix_decks_created_at")
    op.drop_index("ix_reviews_reviewed_at")
    op.drop_index("ix_reviews_next_review_date")
    op.drop_index("ix_reviews_flashcard_id")
    op.drop_index("ix_flashcards_deck_id")

    # ### end Alembic commands ###
