"""initial_schema_baseline

Revision ID: f3e3ac684f8e
Revises:
Create Date: 2025-11-07 12:27:15.434175

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3e3ac684f8e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add spaced repetition fields with appropriate defaults
    op.add_column(
        "reviews", sa.Column("ease_factor", sa.Float(), nullable=False, server_default="2.5")
    )
    op.add_column(
        "reviews", sa.Column("interval_days", sa.Integer(), nullable=False, server_default="1")
    )
    op.add_column(
        "reviews", sa.Column("repetitions", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "repetitions")
    op.drop_column("reviews", "interval_days")
    op.drop_column("reviews", "ease_factor")
    # ### end Alembic commands ###
