"""initial_schema_baseline

Revision ID: f3e3ac684f8e
Revises:
Create Date: 2025-11-07 12:27:15.434175

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3e3ac684f8e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create complete base schema with all tables."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create config table
    op.create_table('config',
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('key')
    )

    # Create decks table
    op.create_table('decks',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('source_file', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('last_studied', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Create flashcards table
    op.create_table('flashcards',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('deck_id', sa.String(), nullable=False),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('answer', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create reviews table with all spaced repetition fields
    op.create_table('reviews',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('flashcard_id', sa.String(), nullable=False),
        sa.Column('reviewed_at', sa.DateTime(), nullable=False),
        sa.Column('user_answer', sa.Text(), nullable=False),
        sa.Column('ai_score', sa.Integer(), nullable=False),
        sa.Column('ai_grade', sa.String(), nullable=False),
        sa.Column('ai_feedback', sa.Text(), nullable=False),
        sa.Column('next_review_date', sa.DateTime(), nullable=True),
        sa.Column('ease_factor', sa.Float(), nullable=False, server_default="2.5"),
        sa.Column('interval_days', sa.Integer(), nullable=False, server_default="1"),
        sa.Column('repetitions', sa.Integer(), nullable=False, server_default="0"),
        sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop all base tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('flashcards')
    op.drop_table('decks')
    op.drop_table('config')
    # ### end Alembic commands ###
